### PR TITLE
Fix ILogger instrumentation for non-host console app

### LINKED ISSUE #1292: Add ILogger instrumentation for non-host console app
Add support for "non-host console app" scenario like here: https://learn.microsoft.com/en-us/dotnet/core/extensions/logging?tabs=command-line#non-host-console-app

Possibly it can be achieved by adding bytecode instrumentation.

CC @rajkumar-rangaraj

### PR DESCRIPTION
**Pull request by rajkumar-rangaraj**
## Why

Fixes #1292

OpenTelemetry .NET SDK has reference to [`Microsoft.Extensions.Logging.Configuration`](https://github.com/open-telemetry/opentelemetry-dotnet/blob/7fd37833711e27a02e169de09f3816d1d9557be4/src/OpenTelemetry/OpenTelemetry.csproj#L21). Dotnet Core Console based apps will not have reference to this package. Hence auto-instrumentation ran into an `System.IO.FileNotFoundException` on `Microsoft.Extensions.Logging.Configuration` during logs instrumentation. To resolve the issue added `Microsoft.Extensions.Logging.Configuration` to AdditionalDeps/RuntimeStore.

## What

- Added `Microsoft.Extensions.Logging.Configuration` to `OpenTelemetry.AutoInstrumentation.AdditionalDeps` project.
- Updated `SmokeTests` to include ILogger instrumentation for non-host console app.

## Checklist

- ~~[X] `CHANGELOG.md` is updated.~~
- ~~[X] Documentation is updated.~~
- [X] New features are covered by tests.

### CODE REVIEW

File: test/IntegrationTests/SmokeTests.cs [hunk 1]
```diff
@@ -191,6 +192,22 @@ public async Task PrometheusExporter()
...
 
+#if !NETFRAMEWORK
+    [Fact]
+    [Trait("Category", "EndToEnd")]
+    public async Task SubmitLogs()
+    {
+        using var collector = await MockLogsCollector.Start(Output);
+        collector.Expect(logRecord => Convert.ToString(logRecord.Body) == "{ \"stringValue\": \"Example log message\" }");
+
+        SetEnvironmentVariable("OTEL_DOTNET_AUTO_LOGS_PARSE_STATE_VALUES", "true");
```
Comment (rajkumar-rangaraj) [inline test/IntegrationTests/SmokeTests.cs:203]: This is needed for the tests to pass. Once the other PR gets merged will remove parse state environment variable.

Comment (pellared) [reply test/IntegrationTests/SmokeTests.cs]: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/1300/commits/ea6fd539335c4607e462fae0d7ee7db247e085a9

File: test/test-applications/integrations/TestApplication.Smoke/Program.cs [hunk 2]
```diff
@@ -19,6 +19,9 @@
 using System.Diagnostics;
 using System.Diagnostics.Metrics;
 using System.Net.Http;
+#if !NETFRAMEWORK
```
Comment (pellared) [inline test/test-applications/integrations/TestApplication.Smoke/Program.cs:22]: Can we remove these `#if !NETFRAMEWORK` in the test app? I think it should not ham. If it would then it would at least manifest a problem.

**Review by pellared — APPROVED** [review]

File: test/test-applications/integrations/TestApplication.Smoke/TestApplication.Smoke.csproj [hunk 3]
```diff
@@ -7,6 +7,10 @@
     <PackageReference Include="System.Diagnostics.DiagnosticSource" Version="6.0.0" />
   </ItemGroup>
 
+  <ItemGroup Condition=" '$(TargetFramework)' != 'net462' ">
```
Comment (pellared) [inline test/test-applications/integrations/TestApplication.Smoke/TestApplication.Smoke.csproj:10]: I suggest adding it for .NET Framework as well.

File: test/test-applications/integrations/TestApplication.Smoke/Program.cs (hunk 2 above)
Comment (rajkumar-rangaraj) [reply test/test-applications/integrations/TestApplication.Smoke/Program.cs:22]: This makes sense, removing `!NETFRAMEWORK`.

**Review by pellared — APPROVED** [review]
