### PR TITLE
WCF instrumentation on .NET Framework

### LINKED ISSUE #1704: WCF instrumentation does not work with release 0.5.0
# Bug Report

## Symptom

**Describe the bug**
WCF instrumentation does not work with release 0.5.0. I noticed lazy instrumentation was applied to WCF in this release, and the required assembly is [System.ServiceModel.Primitives](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/c7781798ac34d38f1e4f98e0e163ed1a7d1470a3/src/OpenTelemetry.AutoInstrumentation/Loading/Initializers/WcfInitializer.cs#L28). 
in my WCF sample, that assembly didnot get loaded (attached please find a screenshot). Can we make change to the WCF required assembly, or make the assembly name configurable using an env variable to override the default value?
wcf_lazy_instr

**Expected behavior**
WCF instrumentation should work

**Runtime environment:**

- OpenTelemetry Automatic Instrumentation version: 0.5.0
- OS: Windows 10
- .NET version: .NET Framework 4.6.2

### PR DESCRIPTION
**Pull request by dszmigielski**
## Why

We cannot require `System.ServiceModel.Primitives` to be loaded for WCF on .NET Framework, as it is not necessary for .NET Framework implementation.

Fixes #1704

## What

Change assembly required for lazy initialization of WCF on .NET Framework to `System.ServiceModel`.

## Tests

.NET Framework test applications were changed so they don't load `System.ServiceModel.Primitives`, tests were failing after this change: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/actions/runs/3694491904/jobs/6255742173

After changing required assembly tests pass once again: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/actions/runs/3694988032/jobs/6256835895

## Checklist

- [x] `CHANGELOG.md` is updated.
- [x] Documentation is updated.
- [x] New features are covered by tests.

### CODE REVIEW

**Review by theletterf — APPROVED** [review]

File: src/OpenTelemetry.AutoInstrumentation/Loading/Initializers/WcfInitializer.cs [hunk 1]
```diff
@@ -25,7 +25,11 @@ internal class WcfInitializer : InstrumentationInitializer
     private readonly PluginManager _pluginManager;
 
     public WcfInitializer(PluginManager pluginManager)
+#if NETFRAMEWORK
+        : base("System.ServiceModel")
+#else
         : base("System.ServiceModel.Primitives")
```
Comment (Kielek) [inline src/OpenTelemetry.AutoInstrumentation/Loading/Initializers/WcfInitializer.cs:31]: Is there any chance that .NET (Core) will not load this library?
I mean in the same scenario as for .NET Fx.

File: test/test-applications/integrations/TestApplication.Wcf.Client.NetFramework/TestApplication.Wcf.Client.NetFramework.csproj [hunk 2]
```diff
@@ -1,13 +1,9 @@
 ﻿<Project Sdk="Microsoft.NET.Sdk">
 
   <PropertyGroup>
-    <TargetFrameworks>net462</TargetFrameworks>
+    <TargetFramework>net462</TargetFramework>
```
Comment (Kielek) [inline test/test-applications/integrations/TestApplication.Wcf.Client.NetFramework/TestApplication.Wcf.Client.NetFramework.csproj:4]: I would keep TargetFrameworks, even if you are using only one Framework.
This property is configured at the props file changing it to singular form could leads to unexpected scenarios.

File: test/test-applications/integrations/TestApplication.Wcf.Server.NetFramework/TestApplication.Wcf.Server.NetFramework.csproj [hunk 3]
```diff
@@ -1,13 +1,9 @@
 ﻿<Project Sdk="Microsoft.NET.Sdk">
 
   <PropertyGroup>
-    <TargetFrameworks>net462</TargetFrameworks>
+    <TargetFramework>net462</TargetFramework>
```
Comment (Kielek) [inline test/test-applications/integrations/TestApplication.Wcf.Server.NetFramework/TestApplication.Wcf.Server.NetFramework.csproj:4]: TargetFramework -> TargetFrameworks

File: src/OpenTelemetry.AutoInstrumentation/Loading/Initializers/WcfInitializer.cs (hunk 1 above)
Comment (dszmigielski) [reply src/OpenTelemetry.AutoInstrumentation/Loading/Initializers/WcfInitializer.cs:31]: `ServiceContractAttribute` is defined in `System.ServiceModel.Primitives` assembly for .NET Core, so you need to reference it to define the contract.

**Review by Kielek — APPROVED** [review]

**Review by pjanotti — APPROVED** [review]
