### PR TITLE
`ILogger` integration fix for `net6` when `WebApplicationBuilder` is used

### LINKED ISSUE #2994: Exported logs duplication for some ASP.NET core web apps on `net6`
# Bug Report

## Symptom

**Describe the bug**
Logs are exported multiple times from application created with minimal api template (e.g dotnet new web).

**Expected behavior**
Logs should be exported once.

**Runtime environment (please complete the following information):**

- OpenTelemetry Automatic Instrumentation version: v1.0.2
- OS: win10
- .NET version: net6.0

**Additional context**
Issue seems to be connected with recent change: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/2975
No issues when v1.0.1 of autoinstrumentation is used.
No issue with v1.0.2 on `net7.0`.
No issue with v1.0.2 on `net6.0` for existing [web app](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/tree/main/test/test-applications/integrations/TestApplication.Logs) used for testing logs export.

## Reproduce

See sample application and test on [fork](https://github.com/lachmatt/opentelemetry-dotnet-instrumentation/commit/d57fca611fa8f7e43a0741bf2d4d15a4a8eac5dc).

PTAL @rajkumar-rangaraj

### PR DESCRIPTION
**Pull request by lachmatt**
## Why

Fixes #2994 

## What

Logs are exported multiple times for ASP.NET Core apps targeting `net6` when `WebApplicationBuilder` is used.
In such scenario, integration is called on 2 related service collections: `WebApplicationServiceCollection` and `ServiceCollection`.
Integration tries to detect if it was called before on given `IServiceCollection` instance, but it doesn't work in this case, as it is called on `ServiceCollection` instance before services are copied to it from `WebApplicationServiceCollection` instance (on which integration was called before). This results in same logs being exported 4 times (duplicated loggers with duplicated processors).

Before #2975, integration was not being called if `builder.Services` was not of `ServiceCollection` type. That caused an issue when `HostingStartupAssembly` was configured to enable the integration (and bytecode instrumentation was disabled) for apps targeting `net6` when `WebApplicationBuilder` was used.

The fix checks if `HostingStartupAssembly` is configured, and doesn't run integration for `net6` when `WebApplicationBuilder` is used on host's `ServiceCollection` instance (`OpenTelemetryLogger` related services will be copied from `WebApplicationServiceCollection` instance, for which integration was called from `HostingStartupAssembly`).

All of the problematic scenarios ([one](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/44c1babf833093522ba689acdd416876d9268eaf/test/IntegrationTests/MinimalApiTests.cs#L35) that didn't work before #2975 and [two](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/44c1babf833093522ba689acdd416876d9268eaf/test/IntegrationTests/MinimalApiTests.cs#L33C6-L33C6) that are being fixed with the PR) are covered by tests added in this PR.

Note:
As tests are waiting fixed amount of time to verify logs were not exported multiple times, this adds some time to the CI.

@rajkumar-rangaraj PTAL

## Tests

Included in PR.

## Checklist

- [x] `CHANGELOG.md` is updated.
~~- [ ] Documentation is updated.~~
- [x] New features are covered by tests.

### CODE REVIEW

**Comment by lachmatt** [comment]
Looking into CI failure for `macos`

File: src/OpenTelemetry.AutoInstrumentation/Logger/LogBuilderExtensions.cs [hunk 1]
```diff
@@ -96,5 +116,31 @@ public static ILoggingBuilder AddOpenTelemetryLogs(this ILoggingBuilder builder)
...
+
+    private static bool IsNet6()
+    {
+        var frameworkDescription = FrameworkDescription.Instance;
+        return frameworkDescription.Name == ".NET" && frameworkDescription.ProductVersion.StartsWith("6");
+    }
+
+    private static bool IsHostServiceCollection(IServiceCollection builderServices)
+    {
+        _applicationLifetimeType ??= Type.GetType("Microsoft.Extensions.Hosting.Internal.ApplicationLifetime, Microsoft.Extensions.Hosting");
```
Comment (pjanotti) [inline src/OpenTelemetry.AutoInstrumentation/Logger/LogBuilderExtensions.cs:135]: This will load the mentioned referenced assembly, it should be fine, but, calling attention to this fact.

**Review by pjanotti — COMMENTED** [review]
Took a quick pass, it lgtm at this time, will do a more detailed pass when it is not draft anymore.

File: src/OpenTelemetry.AutoInstrumentation/Logger/LogBuilderExtensions.cs (hunk 1 above)
Comment (lachmatt) [reply src/OpenTelemetry.AutoInstrumentation/Logger/LogBuilderExtensions.cs:135]: Good point. I initially assumed this is fine, but started to have some doubts. I plan to improve it.

File: src/OpenTelemetry.AutoInstrumentation/Logger/LogBuilderExtensions.cs [hunk 2]
```diff
@@ -96,5 +116,31 @@ public static ILoggingBuilder AddOpenTelemetryLogs(this ILoggingBuilder builder)
...
+        var applicationLifetimeDescriptor = builderServices.FirstOrDefault(sd => sd.ImplementationType == _applicationLifetimeType);
+        return applicationLifetimeDescriptor != null;
+    }
+
+    private static bool IsAutoInstrumentationStartupAssemblySet()
+    {
+        var environmentVariable = Environment.GetEnvironmentVariable("ASPNETCORE_HOSTINGSTARTUPASSEMBLIES");
```
Comment (rajkumar-rangaraj) [inline src/OpenTelemetry.AutoInstrumentation/Logger/LogBuilderExtensions.cs:142]: This could throw SecurityException.

File: src/OpenTelemetry.AutoInstrumentation/Logger/LogBuilderExtensions.cs [hunk 3]
```diff
@@ -96,5 +116,31 @@ public static ILoggingBuilder AddOpenTelemetryLogs(this ILoggingBuilder builder)
 
         return builder;
     }
+
+    private static bool IsAutoInstrumentationStartupAssemblyConfigured()
```
Comment (rajkumar-rangaraj) [inline src/OpenTelemetry.AutoInstrumentation/Logger/LogBuilderExtensions.cs:120]: Why do we need this method? We could directly call `IsAutoInstrumentationStartupAssemblySet`.
Additionally, the comment in this method might be incorrect. Bytecode instrumentation is called before HostingStartupAssembly, so the integration might not have occurred yet. Since HostingStartupAssembly is set, we expect `OpenTelemetry.AutoInstrumentation.AspNetCoreBootstrapper` to handle the logger integration at a later time.

File: src/OpenTelemetry.AutoInstrumentation/Logger/LogBuilderExtensions.cs [hunk 4]
```diff
@@ -25,7 +25,27 @@ namespace OpenTelemetry.AutoInstrumentation.Logger;
...
+        // OpenTelemetryLogger-related services were already added to WebApplicationServiceCollection and will
+        // be copied to host's ServiceCollection later. We can't depend on integration's
+        // capability to detect if integration was called before (by checking if ServiceDescriptor with
+        // given type is already added to ServiceCollection) as copying services from WebApplicationServiceCollection
+        // to host's ServiceCollection happens AFTER integration is called.
+
+        // All of this additional checking is NOT needed for net7. There we can rely on integration's capability
+        // to detect if integration was called before, because WebApplicationServiceCollection is not used when building host.
+
+        if (builder.Services is ServiceCollection && !(IsNet6() && IsAutoInstrumentationStartupAssemblyConfigured() && IsHostServiceCollection(builder.Services)))
```
Comment (rajkumar-rangaraj) [inline src/OpenTelemetry.AutoInstrumentation/Logger/LogBuilderExtensions.cs:44]: Should we only check `IsNet6` and `IsAutoInstrumentationStartupAssemblyConfigured`, and use a static bool to ensure the integration has already been done? If static doesn't work, we could also rely on a temporary environment variable

File: CHANGELOG.md [hunk 5]
```diff
@@ -28,6 +28,9 @@ This component adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.h
 
 ### Fixed
 
+- Fixed log emission issue for ASP.NET Core 6.0 apps when bytecode
```
Comment (rajkumar-rangaraj) [inline CHANGELOG.md:31]: Please explain what is the issue in detail stating multiple logs are emitted.

File: src/OpenTelemetry.AutoInstrumentation/Logger/LogBuilderExtensions.cs (hunk 1 above)
Comment (lachmatt) [reply src/OpenTelemetry.AutoInstrumentation/Logger/LogBuilderExtensions.cs]: Adjusted in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/3003/commits/7c21fba9d835536f6d191cc9121b48933fe8dd92

File: src/OpenTelemetry.AutoInstrumentation/Logger/LogBuilderExtensions.cs (hunk 2 above)
Comment (lachmatt) [reply src/OpenTelemetry.AutoInstrumentation/Logger/LogBuilderExtensions.cs:168]: Can you give a sample scenario when you would expect it to fail with that exception?

File: CHANGELOG.md (hunk 5 above)
Comment (lachmatt) [reply CHANGELOG.md]: Explained in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/3003/commits/7c21fba9d835536f6d191cc9121b48933fe8dd92

File: test/IntegrationTests/MinimalApiTests.cs [hunk 6]
```diff
@@ -0,0 +1,69 @@
...
+using IntegrationTests.Helpers;
+using OpenTelemetry.Proto.Logs.V1;
+using Xunit.Abstractions;
+
+namespace IntegrationTests;
+
+public class MinimalApiTests : TestHelper
+{
+    public MinimalApiTests(ITestOutputHelper output)
+        : base("MinimalApi", output)
```
[the remark this answers is not in the document]
Comment (lachmatt) [reply test/IntegrationTests/MinimalApiTests.cs:30]: Can you explain why is it preferred to adjust `TestApplication.Razor` instead of using the new test application?
I'd prefer to keep this new test application, as it is minimal example that reproduced the issue.

**Comment by lachmatt** [comment]
> Looking into CI failure for `macos` (TestHost process is crashing)

I ran smoke test when bytecode instrumentation was not enabled, and it still crashed. It seems to be connected to addition of new kind of test app, I think this could be fixed as a part of separate issue. For now, I skipped problematic scenario.

File: src/OpenTelemetry.AutoInstrumentation/Logger/LogBuilderExtensions.cs (hunk 3 above)
Comment (lachmatt) [reply src/OpenTelemetry.AutoInstrumentation/Logger/LogBuilderExtensions.cs:120]: This is here to ensure we check environment variable once, assuming we want to support scenarios as described in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/3003#discussion_r1358171530

File: src/OpenTelemetry.AutoInstrumentation/Logger/LogBuilderExtensions.cs (hunk 4 above)
Comment (rajkumar-rangaraj) [reply src/OpenTelemetry.AutoInstrumentation/Logger/LogBuilderExtensions.cs:44]: I understand, but not comfortable in using this check `builder.Services is ServiceCollection` as we know this has caused issues earlier and we released a minor version for it.

File: src/OpenTelemetry.AutoInstrumentation/Logger/LogBuilderExtensions.cs (hunk 3 above)
Comment (rajkumar-rangaraj) [reply src/OpenTelemetry.AutoInstrumentation/Logger/LogBuilderExtensions.cs:120]: Checking an environment variable is not a big cost, better to simplify the code here.

File: src/OpenTelemetry.AutoInstrumentation/Logger/LogBuilderExtensions.cs (hunk 2 above)
Comment (rajkumar-rangaraj) [reply src/OpenTelemetry.AutoInstrumentation/Logger/LogBuilderExtensions.cs:168]: Reference: https://learn.microsoft.com/en-us/dotnet/api/system.environment.getenvironmentvariable?view=net-7.0#system-environment-getenvironmentvariable(system-string)

File: test/IntegrationTests/MinimalApiTests.cs (hunk 6 above)
[the remark this answers is not in the document]
Comment (rajkumar-rangaraj) [reply test/IntegrationTests/MinimalApiTests.cs:30]: According to me both `TestApplication.Razor` and `MinimalApiTests` are same, we are creating duplicate test apps here. Its better to modify the Razor test with the implementation added here.

File: src/OpenTelemetry.AutoInstrumentation/Logger/LogBuilderExtensions.cs (hunk 2 above)
Comment (lachmatt) [reply src/OpenTelemetry.AutoInstrumentation/Logger/LogBuilderExtensions.cs]: changed in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/3003/commits/4553d4aa02e202baf609a8cbb2d5765c02194962

File: test/IntegrationTests/MinimalApiTests.cs (hunk 6 above)
[the remark this answers is not in the document]
Comment (lachmatt) [reply test/IntegrationTests/MinimalApiTests.cs:30]: `TestApplication.Razor`, compared to `TestApplication.MinimalApi`, has additional configuration/services added related to razor pages, which are not relevant as far as issue is concerned.
What do you think about removing `RazorTests` and `TestApplication.Razor`?

[the remark this answers is not in the document]
Comment (rajkumar-rangaraj) [reply test/IntegrationTests/MinimalApiTests.cs:30]: Yes, keep either of them. No strong preference.

[the remark this answers is not in the document]
Comment (lachmatt) [reply test/IntegrationTests/MinimalApiTests.cs:30]: Removed `RazorTests` and `TestApplication.Razor` in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/3003/commits/8451ff45c3b3fb9279d199091d647105f2a4a086
I also added test application created with worker template (uses generic host).

File: OpenTelemetry.AutoInstrumentation.sln [hunk 7]
```diff
@@ -203,7 +203,9 @@ Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "TestApplication.Azure", "te
 EndProject
 Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "TestApplication.Wcf.Client.DotNet", "test\test-applications\integrations\TestApplication.Wcf.Client.DotNet\TestApplication.Wcf.Client.DotNet.csproj", "{EDE168E0-DBCD-4DE3-B55A-4B633ED6565E}"
 EndProject
-Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "TestApplication.Razor", "test\test-applications\integrations\TestApplication.Razor\TestApplication.Razor.csproj", "{1C76773E-2582-40DB-A720-3798E3928876}"
+Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "TestApplication.MinimalApi", "test\test-applications\integrations\TestApplication.MinimalApi\TestApplication.MinimalApi.csproj", "{803A3DD1-016E-4713-8066-A1C81A6ADBA3}"
```
Comment (rajkumar-rangaraj) [inline OpenTelemetry.AutoInstrumentation.sln:206]: I don't see the entry removed for TestApplication.Razor.

File: src/OpenTelemetry.AutoInstrumentation/Logger/LogBuilderExtensions.cs [hunk 8]
```diff
@@ -96,5 +124,44 @@ public static ILoggingBuilder AddOpenTelemetryLogs(this ILoggingBuilder builder)
...
+    {
+        var frameworkDescription = FrameworkDescription.Instance;
+        return frameworkDescription.Name == ".NET" && frameworkDescription.ProductVersion.StartsWith("6");
+    }
+
+    private static bool IsHostServiceCollection(IServiceCollection builderServices)
+    {
+        // check if assembly is loaded before trying to get type,
+        // in order to avoid triggering an unnecessary load
+        var assemblies = AppDomain.CurrentDomain.GetAssemblies();
```
Comment (rajkumar-rangaraj) [inline src/OpenTelemetry.AutoInstrumentation/Logger/LogBuilderExtensions.cs:138]: We can avoid this check as Type.GetType won't load the assembly if it's already loaded.

**Review by rajkumar-rangaraj — APPROVED** [review]
LGTM. I've left a few minor comments to address.

File: src/OpenTelemetry.AutoInstrumentation/Logger/LogBuilderExtensions.cs (hunk 3 above)
Comment (lachmatt) [reply src/OpenTelemetry.AutoInstrumentation/Logger/LogBuilderExtensions.cs]: removed in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/3003/commits/4d7b009fc77838ae84c72345bd409bd20dbca44f

File: OpenTelemetry.AutoInstrumentation.sln (hunk 7 above)
Comment (Kielek) [reply OpenTelemetry.AutoInstrumentation.sln:206]: Git decided to rename Razor to MinimalApi. It was so similar.

File: src/OpenTelemetry.AutoInstrumentation/Logger/LogBuilderExtensions.cs (hunk 8 above)
Comment (lachmatt) [reply src/OpenTelemetry.AutoInstrumentation/Logger/LogBuilderExtensions.cs]: removed in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/3003/commits/0c129a81f0e8f710bfbfe45f1bcab2c30543d7b9

**Review by Kielek — APPROVED** [review]
