### PR TITLE
Initialize profiler only when it is enabled

### LINKED ISSUE #2563: Suppress Event Source error when CLR profiler is not set
# Bug Report

When CLR profiler is not used by auto-instrumentation, it logs the below message as error. `NativeMethods.Windows.InitializeProfiler` should be called only when CLR profiler based environment variables are set.

<BODY>
<TABLE><TR><TD>Event Name &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD> Time MSec</TD><TD>Process Name &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD>Rest &nbsp;</TD></TR><TR><TD>OpenTelemetry-AutoInstrumentation/Error</TD><TD>17,347.495</TD><TD>Process(51768) (51768)</TD><TD>ThreadID=&quot;49,272&quot; FormattedMessage=&quot;Unable to load DLL 'OpenTelemetry.AutoInstrumentation.Native.dll' or one of its dependencies: The specified module could not be found. (0x8007007E) Exception: Unable to load DLL 'OpenTelemetry.AutoInstrumentation.Native.dll' or one of its dependencies: The specified module could not be found. (0x8007007E) System.DllNotFoundException: Unable to load DLL 'OpenTelemetry.AutoInstrumentation.Native.dll' or one of its dependencies: The specified module could not be found. (0x8007007E) at OpenTelemetry.AutoInstrumentation.NativeMethods.Windows.InitializeProfiler(String id, NativeCallTargetDefinition[] methodArrays, Int32 size) at OpenTelemetry.AutoInstrumentation.Instrumentation.Initialize() &quot; message=&quot;Unable to load DLL 'OpenTelemetry.AutoInstrumentation.Native.dll' or one of its dependencies: The specified module could not be found. (0x8007007E) Exception: Unable to load DLL 'OpenTelemetry.AutoInstrumentation.Native.dll' or one of its dependencies: The specified module could not be found. (0x8007007E) System.DllNotFoundException: Unable to load DLL 'OpenTelemetry.AutoInstrumentation.Native.dll' or one of its dependencies: The specified module could not be found. (0x8007007E) at OpenTelemetry.AutoInstrumentation.NativeMethods.Windows.InitializeProfiler(String id, NativeCallTargetDefinition[] methodArrays, Int32 size) at OpenTelemetry.AutoInstrumentation.Instrumentation.Initialize()&quot; </TD></TR></TABLE>

</BODY>

### PR DESCRIPTION
**Pull request by Kielek**
## Why

Fixes #2563

## What

Initialize profiler only when it is enabled.

## Tests

CI + local verification

## Checklist

- ~~[ ] `CHANGELOG.md` is updated.~~
- ~~[ ] Documentation is updated.~~
- ~~[ ] New features are covered by tests.~~

## Notes
I was considering to put conditional calls directly in NativeMethods class, but it will cause unnecessary preparation for local and plugins definitions.

In theory, someone can have only non-OTel profiler attached. I think that we can accept that risk.

### CODE REVIEW

File: src/OpenTelemetry.AutoInstrumentation/Instrumentation.cs [hunk 1]
```diff
@@ -177,35 +177,42 @@ public static void Initialize()
             throw;
         }
 
-        RegisterInstrumentations(InstrumentationDefinitions.GetAllDefinitions());
-
-        try
+        if (GeneralSettings.Value.ProfilerEnabled)
         {
-            foreach (var payload in _pluginManager.GetAllDefinitionsPayloads())
+            RegisterInstrumentations(InstrumentationDefinitions.GetAllDefinitions());
```
Comment (pellared) [inline src/OpenTelemetry.AutoInstrumentation/Instrumentation.cs:182]: Can we rename `RegisterInstrumentations` to `RegisterByteCodeInstrumentations` to make it obvious that source-code instrumentations will still work?

**Review by pellared — APPROVED** [review]

File: src/OpenTelemetry.AutoInstrumentation/Instrumentation.cs [hunk 2]
```diff
@@ -177,35 +177,42 @@ public static void Initialize()
...
+            catch (Exception ex)
+            {
+                Logger.Error(ex, ex.Message);
+            }
         }
-        catch (Exception ex)
+        else
         {
-            Logger.Error(ex, ex.Message);
+            Logger.Debug("Skipping profiler initialization. {0} is disabled", ConfigurationKeys.ProfilingEnabled);
```
Comment (pjanotti) [inline src/OpenTelemetry.AutoInstrumentation/Instrumentation.cs:215]:
```suggestion
            Logger.Debug("Skipping CLR Profiler initialization. {0} environment variable was not set to '1'.", ConfigurationKeys.ProfilingEnabled);
```

Comment (pjanotti) [reply src/OpenTelemetry.AutoInstrumentation/Instrumentation.cs:215]: It is fine for completeness and keeping the code symmetrical, but, I don't think it is possible for this to happen in the .NET Framework, so it will always be `CORECLR_ENABLE_PROFILING`.

**Review by pjanotti — APPROVED** [review]

File: src/OpenTelemetry.AutoInstrumentation/Instrumentation.cs (hunk 2 above)
Comment (Kielek) [reply src/OpenTelemetry.AutoInstrumentation/Instrumentation.cs:215]: You are right. Technically this check makes sense only on .NET.
It cannot happen for .NET Framework, but I think it is better than creating conditional compilation.
