### PR TITLE
Make sure excluded assets are removed

### LINKED ISSUE #1150: Remove StackExchange.Redis library from auto-instrumentation package
# Bug Report

## Symptom

**Describe the bug**
`StackExchange.Redis.dll` library is present in the `tracer-home` folder. 

**Expected behavior**
We should remove this library from our package and utilize the reference from customer app.

There are other libraries like `MySql.Data.dll`, `Pipelines.Sockets.Unofficial.dll` which needs to be removed. If we plan to use it we may need to review the license information for these project.

### PR DESCRIPTION
**Pull request by Kielek**
## Why

Fixes #1150

## What

Remove excluded assets from our distribution such as:
* `StackExchange.Redis`
* `MySql.Data`
* `Pipelines.Sockets.Unofficial`

## Tests

CI + Manual verification

## Checklist

- ~~[ ] `CHANGELOG.md` is updated.~~
- ~~[ ] Documentation is updated.~~
- [x] ~~New~~ features are covered by tests.

### CODE REVIEW

**Review by RassK — APPROVED** [review]

**Review by pellared — APPROVED** [review]

**Review by pellared — APPROVED** [review]

File: test/IntegrationTests/CommonTests.cs [hunk 1]
```diff
@@ -0,0 +1,41 @@
...
+
+using System.IO;
+using FluentAssertions;
+using FluentAssertions.Execution;
+using IntegrationTests.Helpers;
+using Xunit;
+
+namespace IntegrationTests;
+
+public class CommonTests
```
Comment (pellared) [inline test/IntegrationTests/CommonTests.cs:25]: How about renaming `BuildTests`?

File: test/IntegrationTests/CommonTests.cs [hunk 2]
```diff
@@ -0,0 +1,41 @@
...
+    public void DistributionDoesNotContainExcludedAssets()
+    {
+        var distributionFolder = EnvironmentHelper.GetNukeBuildOutput();
+        var files = Directory.GetFiles(distributionFolder, "*", SearchOption.AllDirectories);
+
+        using (new AssertionScope())
+        {
+            foreach (var file in files)
+            {
+                file.Should().NotContainAny("StackExchange.Redis", "MySql.Data", "Pipelines.Sockets.Unofficial");
```
[the remark this answers is not in the document]
Comment (Kielek) [reply test/IntegrationTests/CommonTests.cs:37]: We could use Verify functionality with dumped structure. I think it could be separate PR/task.

File: test/IntegrationTests/CommonTests.cs (hunk 1 above)
Comment (Kielek) [reply test/IntegrationTests/CommonTests.cs:25]: Sure. I do not have access to computer. I can fix it on Monday. If you want, fell free to change on my branch today.

File: src/OpenTelemetry.AutoInstrumentation.AspNetCoreBootstrapper/OpenTelemetry.AutoInstrumentation.AspNetCoreBootstrapper.csproj [hunk 3]
```diff
@@ -1,5 +1,7 @@
 ﻿<Project Sdk="Microsoft.NET.Sdk">
 
+  <Import Project="..\CommonExcludedAssets.props" />
```
Comment (rajkumar-rangaraj) [inline src/OpenTelemetry.AutoInstrumentation.AspNetCoreBootstrapper/OpenTelemetry.AutoInstrumentation.AspNetCoreBootstrapper.csproj:3]: This project does only logger work and does not require any of the packages in `CommonExcludedAssets.props` as all of those are related to traces. 

We have a project reference to `OpenTelemetry.AutoInstrumentation.csproj` and that indirectly adds assets to the our package even when excluded in parent project. This could be a dotnet bug. 

This line of code could act as a workaround, but its better to leave a comment saying it is not used by this project and only added to avoid assets.

**Review by rajkumar-rangaraj — APPROVED** [review]

File: src/OpenTelemetry.AutoInstrumentation.AspNetCoreBootstrapper/OpenTelemetry.AutoInstrumentation.AspNetCoreBootstrapper.csproj (hunk 3 above)
Comment (pjanotti) [reply src/OpenTelemetry.AutoInstrumentation.AspNetCoreBootstrapper/OpenTelemetry.AutoInstrumentation.AspNetCoreBootstrapper.csproj:3]: What the bootstrapper uses from `OpenTelemetry.AutoInstrumentation.csproj`? Because it is used for the bytecode injection it is preferable that we only load `OpenTelemetry.AutoInstrumentation` when doing bytecode injection. That said is not a hard requirement, but, something that I may want to do while fixing strong name (otherwise we have to strong name a bunch of projects because of the cascading nature of strong name).

Comment (rajkumar-rangaraj) [reply src/OpenTelemetry.AutoInstrumentation.AspNetCoreBootstrapper/OpenTelemetry.AutoInstrumentation.AspNetCoreBootstrapper.csproj:3]: Bootstrapper uses `LogSettings` from `OpenTelemetry.AutoInstrumentation.csproj`. Other option is to move the configuration read to a shared project.

Comment (pjanotti) [reply src/OpenTelemetry.AutoInstrumentation.AspNetCoreBootstrapper/OpenTelemetry.AutoInstrumentation.AspNetCoreBootstrapper.csproj:3]: Thanks. No need to change it right now but something to consider carefully.

**Review by pjanotti — APPROVED** [review]

File: src/OpenTelemetry.AutoInstrumentation.AspNetCoreBootstrapper/OpenTelemetry.AutoInstrumentation.AspNetCoreBootstrapper.csproj (hunk 3 above)
Comment (pjanotti) [reply src/OpenTelemetry.AutoInstrumentation.AspNetCoreBootstrapper/OpenTelemetry.AutoInstrumentation.AspNetCoreBootstrapper.csproj:3]: Also since the AspNet module is for .NET core the strong name can be ignored.

File: test/IntegrationTests/CommonTests.cs (hunk 1 above)
Comment (pellared) [reply test/IntegrationTests/CommonTests.cs]: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/1151/commits/a78ce3c39f4bdac02746fcd52172d684b045c4db

**Comment by pellared** [comment]
@Kielek merging. Feel free to address comments in new PRs 😉

**Review by nrcventura — APPROVED** [review]
