### PR TITLE
Replace span.kind tag by ActivityKind

### LINKED ISSUE #1283: ActivityKind is always 'internal' for bytecode intrumentation
# Bug Report

## Symptom

**Describe the bug**
[activitySource.StartActivity(operationName)](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/de45afdb36733468fa2e78a7ba7197d54abc0c73/src/OpenTelemetry.AutoInstrumentation/Util/ActivityHelper.cs#L42) will use `internal` as default ActivityKind and it can not be changed after activity is started. 

I tried to add tag with ActivityKind = client, it turned out that there will be 2 `kind` tags in the final activity: one is `internal`; the other is `client`.

So suggest to add input argument ActivityKind to [activitySource.StartActivity()](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/de45afdb36733468fa2e78a7ba7197d54abc0c73/src/OpenTelemetry.AutoInstrumentation/Util/ActivityHelper.cs#L42)

**Runtime environment:**

- OpenTelemetry Automatic Instrumentation version: 0.3.1
- OS: Windows 10
- .NET version: .NET Framework 4.6.2

### PR DESCRIPTION
**Pull request by Kielek**
## Why

Fixes #1283

## What

Replace `span.kind` tag by `ActivityKind`
It is serialized by as span `kind` property.

## Tests

CI + extended tests.

## Checklist

- [x] `CHANGELOG.md` is updated.
- ~~[ ] Documentation is updated.~~
- [x] ~~New~~ features are covered by tests.

## Notes
There were no assertions on `WebServerSpanExpectation` so I have removed this class.

### CODE REVIEW

**Comment by Kielek** [comment]
@muhaook, thanks for reporting #1283. Could you please verify proposed changes?

File: src/OpenTelemetry.AutoInstrumentation/Util/ActivityHelper.cs [hunk 1]
```diff
@@ -70,4 +59,20 @@ internal static void DisposeWithException(this Activity activity, Exception exce
             }
         }
     }
+
+    private static Activity StartActivityWithTags(this ActivitySource activitySource, string operationName, ActivityKind kind, ITags tags)
+    {
+        var activity = activitySource.StartActivity(operationName, kind);
+
```
Comment (pellared) [inline src/OpenTelemetry.AutoInstrumentation/Util/ActivityHelper.cs:66]: How about adding

```suggestion
        var activity = activitySource.StartActivity(operationName, kind);
        if (activity == null)
        {
            return null;
        }
```

to reduce the possibility of throwing a NullPointerException? 

It should fix https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/1282

I think we should be very careful and make sure we never throw an exception at runtime.

**Review by pellared — APPROVED** [review]

**Review by nrcventura — APPROVED** [review]

**Comment by muhaook** [comment]
looks good to me[👍](https://whatemoji.org/blog/thumbs-up-emoji-guide/#:~:text=The%20%F0%9F%91%8D%20Thumbs%20Up%20emoji%20is%20optimistic.%20Everything,that%20you%20like%20something%20and%20approve%20of%20it.) Thanks

File: src/OpenTelemetry.AutoInstrumentation/Instrumentations/GraphQL/GraphQLCommon.cs [hunk 2]
```diff
@@ -61,7 +61,7 @@ internal static Activity CreateActivityFromExecuteAsync(IExecutionContext execut
                 tags.Document = query;
             }
 
-            activity = ActivitySource.StartActivityWithTags(operation, tags);
+            activity = ActivitySource.StartServerActivityWithTags(operation, tags);
```
[the remark this answers is not in the document]
Comment (pjanotti) [reply src/OpenTelemetry.AutoInstrumentation/Instrumentations/GraphQL/GraphQLCommon.cs:64]: In principle I think that we should keep it as a server span: the instrumentation should be independent of each other. Anyway, let's handle that separately. We can talk about it at the next SIG meeting.

File: src/OpenTelemetry.AutoInstrumentation/Util/ActivityHelper.cs [hunk 3]
```diff
@@ -70,4 +59,20 @@ internal static void DisposeWithException(this Activity activity, Exception exce
             }
         }
     }
+
+    private static Activity StartActivityWithTags(this ActivitySource activitySource, string operationName, ActivityKind kind, ITags tags)
```
Comment (pjanotti) [inline src/OpenTelemetry.AutoInstrumentation/Util/ActivityHelper.cs:63]: Why not make this one public and remove `StartServerActivityWithTags`?

**Review by pjanotti — APPROVED** [review]
LGTM. I have a suggestion but it is fine either way.

File: src/OpenTelemetry.AutoInstrumentation/Instrumentations/GraphQL/GraphQLCommon.cs (hunk 2 above)
[the remark this answers is not in the document]
Comment (pjanotti) [reply src/OpenTelemetry.AutoInstrumentation/Instrumentations/GraphQL/GraphQLCommon.cs:64]: Note that this slightly differs from the grpc client case suppressing the HttpClient spans under it.

File: src/OpenTelemetry.AutoInstrumentation/Util/ActivityHelper.cs (hunk 1 above)
Comment (Kielek) [reply src/OpenTelemetry.AutoInstrumentation/Util/ActivityHelper.cs:66]: Sure, lets put it into separate PR. I know that it will be small, but maybe there will be a chance to somehow test it.

File: src/OpenTelemetry.AutoInstrumentation/Instrumentations/GraphQL/GraphQLCommon.cs (hunk 2 above)
[the remark this answers is not in the document]
Comment (Kielek) [reply src/OpenTelemetry.AutoInstrumentation/Instrumentations/GraphQL/GraphQLCommon.cs:64]: #1322

File: src/OpenTelemetry.AutoInstrumentation/Util/ActivityHelper.cs (hunk 3 above)
Comment (Kielek) [reply src/OpenTelemetry.AutoInstrumentation/Util/ActivityHelper.cs]: I do not have strong opinion about api shape. Fixed in df41937244b183b81854f6758ea7f3f4c00cd2ba
