### PR TITLE
Fix bug in OTEL_EXPORTER_OTLP_*_PROTOCOL handling for all signals

### LINKED ISSUE #4593: Cannot set to `http/protobuf` with `OTEL_EXPORTER_OTLP_METRICS_PROTOCOL`
# Bug Report

## Symptom

**Describe the bug**
Setting both `OTEL_EXPORTER_OTLP_METRICS_PROTOCOL` to `http/protobuf` and `OTEL_EXPORTER_OTLP_METRICS_ENDPOINT` to `http://localhost:4318/v1/metrics` would cause OTLP metrics exporter to use `gRPC`.

**Expected behavior**

Setting `OTEL_EXPORTER_OTLP_METRICS_PROTOCOL` to `http/protobuf` should make OTLP exporter to use protobuf instead of gRPC.

**Screenshots**

**Runtime environment (please complete the following information):**

- OpenTelemetry Automatic Instrumentation version: [e.g. 1.0.0] v1.13.0-beta.1
- OS: [e.g. Windows Server 2012 R2 ] Windows 11 Enterprise
- .NET version: [e.g. .NET Framework 4.6.2, .NET Core 2.1] 10.0.0-rc.2.25502.107

**Additional context**

If instead of `OTEL_EXPORTER_OTLP_METRICS_PROTOCOL`, I set `OTEL_EXPORTER_OTLP_PROTOCOL` to `http/protobuf`, the OTLP metrics would flow.

```
$env:OTEL_EXPORTER_OTLP_METRICS_ENDPOINT = "http://localhost:4318/v1/metrics"
$env:OTEL_EXPORTER_OTLP_PROTOCOL="http/protobuf"
$env:OTEL_METRICS_EXPORTER="otlp"
```

## Reproduce

 1. Install latest version and run Aspire (or OTLP Collector);

```powershell
$module_url = "https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/releases/download/v1.13.0-beta.1/OpenTelemetry.DotNet.Auto.psm1"
$download_path = Join-Path $env:temp "OpenTelemetry.DotNet.Auto.psm1"
Invoke-WebRequest -Uri $module_url -OutFile $download_path -UseBasicParsing

Import-Module $download_path
Install-OpenTelemetryCore
# Install-OpenTelemetryCore -LocalPath $download_path
Register-OpenTelemetryForCurrentSession -OTelServiceName "MyServiceDisplayName"
```

```
docker run --rm -it `
    -p 18888:18888 `
    -p 4317:18889 `
    -p 4318:18890 `
    -e DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS=true `
    -d `
    --name aspire-dashboard `
    mcr.microsoft.com/dotnet/aspire-dashboard:latest
```

Open <http://localhost:18888/metrics> in browser.

 2. Set env vars and run app;

```powershell
$env:OTEL_EXPORTER_OTLP_METRICS_ENDPOINT = "http://localhost:4318/v1/metrics"
$env:OTEL_EXPORTER_OTLP_METRICS_PROTOCOL="http/protobuf"
$env:OTEL_METRICS_EXPORTER="otlp"

cd C:\repos\opentelemetry-dotnet-instrumentation\examples\playground\AspNetCoreMvc
dotnet build
dotnet bin\Debug\net8.0\Examples.AspNetCoreMvc.dll
```

 3. Validate metrics.

The metrics would fail to load after waiting for 1 minute.

Exception stack shows that OTLP exporter is using **OtlpGrpcExportClient** to send metrics.

```
[2025-11-11T01:50:09.7098569Z] [Information] EventSource=OpenTelemetry-AutoInstrumentation, Message=Logs: Loaded AddOpenTelemetry from LoggingBuilder. 
[2025-11-11T01:51:09.6252424Z] [Error] EventSource=OpenTelemetry-Exporter-OpenTelemetryProtocol, Message=HTTP request to http://localhost:4318/v1/metrics/opentelemetry.proto.collector.metrics.v1.MetricsService/Export failed. Exception: System.Net.Http.HttpRequestException: The HTTP/2 server closed the connection. HTTP/2 error code 'HTTP_1_1_REQUIRED' (0xd). (HttpProtocolError)
 ---> System.Net.Http.HttpProtocolException: The HTTP/2 server closed the connection. HTTP/2 error code 'HTTP_1_1_REQUIRED' (0xd). (HttpProtocolError)
   at System.Net.Http.Http2Connection.ThrowProtocolError(Http2ProtocolErrorCode errorCode, String message)
   at System.Net.Http.Http2Connection.ProcessIncomingFramesAsync()
   at System.Net.Http.Http2Connection.SendHeadersAsync(HttpRequestMessage request, CancellationToken cancellationToken, Boolean mustFlush)
   at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.Metrics.MetricsHandler.SendAsyncWithMetrics(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at OpenTelemetry.Exporter.OpenTelemetryProtocol.Implementation.ExportClient.OtlpExportClient.SendHttpRequest(HttpRequestMessage request, CancellationToken cancellationToken)
   at OpenTelemetry.Exporter.OpenTelemetryProtocol.Implementation.ExportClient.OtlpGrpcExportClient.SendExportRequest(Byte[] buffer, Int32 contentLength, DateTime deadlineUtc, CancellationToken cancellationToken) 
```

<!--
NOTE: If possible, also include the log files found (by default) in:
Windows: %ProgramData%\OpenTelemetry .NET AutoInstrumentation\logs\
Linux and macOS: /var/log/opentelemetry/dotnet/
--!>

<sub>**Tip**: [React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>

### PR DESCRIPTION
**Pull request by xiang17**
## Why

Fixes #4593
Based on existing PR at #4601

`GetExporterOtlpProtocol` ignores the more specific (priority) environment variable and does not pass the value to SDK.

## What

Respect the per-signal variables (`OTEL_EXPORTER_OTLP_<signal>__PROTOCOL`) env vars.

Log a warning and return the default HttpProtobuf option if the env vars are invalid/absent.

## Tests

* Added tests to verify that all priority envs are picked up to manually pass to SDK.

## Checklist

- [x] `CHANGELOG.md` is updated.
- [x] Documentation is updated.
- [x] New features are covered by tests.

### CODE REVIEW

File: src/OpenTelemetry.AutoInstrumentation/Configurations/Otlp/OtlpSettings.cs [hunk 1]
```diff
@@ -161,13 +161,42 @@ private static Uri GetOtlpHttpEndpoint(string? endpoint, OtlpSignalType signalTy
...
+                    if (configuration.FailFast)
+                    {
+                        throw new ArgumentException(
+                            $"OTLP protocol 'grpc' is not supported on .NET Framework in environment variable '{priorityVar}'. Use 'http/protobuf' instead.");
+                    }
+                    else
+                    {
+                        // null value here means that it will be handled by OTEL .NET SDK
+                        return null;
+                    }
```
Comment (ysolomchenko) [inline src/OpenTelemetry.AutoInstrumentation/Configurations/Otlp/OtlpSettings.cs]: My comment from the previous PR also applies here.

https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/4601#discussion_r2526286137

Should we fall back to `HttpProtobuf` since `gRPC` is not supported on the .NET Framework and `FailFast` is set to false?
Additionally, we can log a warning that gRPC is not supported and HttpProtobuf was used instead.

File: src/OpenTelemetry.AutoInstrumentation/Configurations/Otlp/OtlpSettings.cs [hunk 2]
```diff
@@ -161,13 +161,42 @@ private static Uri GetOtlpHttpEndpoint(string? endpoint, OtlpSignalType signalTy
...
+                    return OtlpExportProtocol.HttpProtobuf;
+                default:
+                    if (configuration.FailFast)
+                    {
+                        throw new ArgumentException(
+                            $"Invalid OTLP protocol value '{exporterOtlpProtocol}' in environment variable '{priorityVar}'. Supported values are 'grpc' and 'http/protobuf'.");
+                    }
+
+                    // null value here means that it will be handled by OTEL .NET SDK
+                    return null;
```
Comment (ysolomchenko) [inline src/OpenTelemetry.AutoInstrumentation/Configurations/Otlp/OtlpSettings.cs]: Should we fall back to `HttpProtobuf` as a default when FailFast is set to false?
Additionally, we can log a warning/error that provided value is not supported and HttpProtobuf was used instead.

Comment (rajkumar-rangaraj) [reply src/OpenTelemetry.AutoInstrumentation/Configurations/Otlp/OtlpSettings.cs]: That makes sense. Rather than throwing an error, we can log a message and use HttpProtobuf as the default.

File: src/OpenTelemetry.AutoInstrumentation/Configurations/Otlp/OtlpSettings.cs (hunk 1 above)
Comment (xiang17) [reply src/OpenTelemetry.AutoInstrumentation/Configurations/Otlp/OtlpSettings.cs]: I've updated to log a warning and return the default HttpProtobuf option. As now it's not throwing, I've removed the `FailFast` check now that it's irrelevant.

File: src/OpenTelemetry.AutoInstrumentation/Configurations/Otlp/OtlpSettings.cs (hunk 2 above)
Comment (xiang17) [reply src/OpenTelemetry.AutoInstrumentation/Configurations/Otlp/OtlpSettings.cs]: Same as above, I've updated to log a warning and return the default HttpProtobuf option, and removed the `FailFast` check.

I also read through the definition in the spec and found that it actually called out to not throw an exception:

According to the spec, [the OTEL_METRICS_EXPORTER env var](https://opentelemetry.io/docs/specs/otel/configuration/sdk-environment-variables/#exporter-selection) is an [Enum](https://opentelemetry.io/docs/specs/otel/configuration/sdk-environment-variables/#enum). "For variables accepting an enum value, if the user provides a value the implementation does not recognize, the implementation MUST generate a warning and gracefully ignore the setting."

File: CHANGELOG.md [hunk 3]
```diff
@@ -28,6 +28,9 @@ This component adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.h
 - Setting `DOTNET_STARTUP_HOOKS` is now optional if the .NET CLR profiler
   is configured. If it is not set, the profiler looks for the startup hooks
   assembly and injects the configuration into the application.
+- Fix bug in signal specific OTLP exporter variables: `OTEL_EXPORTER_OTLP_TRACES_PROTOCOL`,
+  `OTEL_EXPORTER_OTLP_METRICS_PROTOCOL` and `OTEL_EXPORTER_OTLP_LOGS_PROTOCOL`.
+  See [#4627](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/4627).
```
Comment (ysolomchenko) [inline CHANGELOG.md]: It should be in a `Fixed` paragraph instead of `Added`.

File: src/OpenTelemetry.AutoInstrumentation/Configurations/Otlp/OtlpSettings.cs [hunk 4]
```diff
@@ -156,18 +159,31 @@ private static Uri GetOtlpHttpEndpoint(string? endpoint, OtlpSignalType signalTy
...
-        if (string.IsNullOrEmpty(exporterOtlpProtocol))
+        if (!string.IsNullOrEmpty(exporterOtlpProtocol))
         {
-            // override settings only for http/protobuf
-            return OtlpExportProtocol.HttpProtobuf;
+            switch (exporterOtlpProtocol)
+            {
+                case "grpc":
+#if NETFRAMEWORK
+                    Logger.Warning($"OTLP protocol 'grpc' is not supported on .NET Framework in environment variable '{priorityVar}'. Changing to 'http/protobuf' instead.");
```
Comment (ysolomchenko) [inline src/OpenTelemetry.AutoInstrumentation/Configurations/Otlp/OtlpSettings.cs]: The priority environment variable value can be null if the user uses only `DefaultProtocolEnvVarName`. This log record can be confusing because the user didn’t set the priority environment variable

File: src/OpenTelemetry.AutoInstrumentation/Configurations/Otlp/OtlpSettings.cs [hunk 5]
```diff
@@ -156,18 +159,31 @@ private static Uri GetOtlpHttpEndpoint(string? endpoint, OtlpSignalType signalTy
...
+                    return OtlpExportProtocol.HttpProtobuf;
+#else
+                    return OtlpExportProtocol.Grpc;
+#endif
+                case "http/protobuf":
+                    return OtlpExportProtocol.HttpProtobuf;
+                default:
+                    Logger.Warning($"Invalid OTLP protocol value '{exporterOtlpProtocol}' in environment variable '{priorityVar}'. Supported values are 'grpc' and 'http/protobuf'. Defaulting to 'http/protobuf'.");
+                    return OtlpExportProtocol.HttpProtobuf;
```
Comment (ysolomchenko) [inline src/OpenTelemetry.AutoInstrumentation/Configurations/Otlp/OtlpSettings.cs]: Same confusing log record.

File: CHANGELOG.md (hunk 3 above)
Comment (xiang17) [reply CHANGELOG.md]: Updated.

File: src/OpenTelemetry.AutoInstrumentation/Configurations/Otlp/OtlpSettings.cs (hunk 4 above)
Comment (xiang17) [reply src/OpenTelemetry.AutoInstrumentation/Configurations/Otlp/OtlpSettings.cs]: Good catch. I've updated and introduced a `usedEnvVarName` to record which env var is used.

File: src/OpenTelemetry.AutoInstrumentation/Configurations/Otlp/OtlpSettings.cs (hunk 5 above)
Comment (xiang17) [reply src/OpenTelemetry.AutoInstrumentation/Configurations/Otlp/OtlpSettings.cs]: Updated.

**Review by nrcventura — APPROVED** [review]
