### PR TITLE
[WCF] Fix WCF instrumentation initialization

### LINKED ISSUE #3589: [bug] OpenTelemetry.Instrumentation.AspNet makes the other middleware failed due to "System.NotSupportedException: Collection is read-only."
### Component

OpenTelemetry.Instrumentation.AspNet

### Package Version

| Package Name                          | Version |
| ------------------------------------- | ------- |
| OpenTelemetry .NET Instrumentation                     | 1.7.0   |

### Runtime Version

net47

### Description

 In my .NET Framework (4.7) application, I have a OWIN based middleware which set a custom header to the HTTP Request.
`public class AuthMiddleware : OwinMiddleware
    {
        public AuthMiddleware(OwinMiddleware next) : base(next) { }

        public override async Task Invoke(IOwinContext context)
        {
            context.Request.Headers["Custom-Header"] = "MyHeaderValue";

            await Next.Invoke(context);
           
        }
    }
}`

When I instrument this application using opentelemetry .net instrumentation power shell script, the application got exception. ( Please see the attached screenshot).
If I just disable the Asp Net instrumentation (OTEL_DOTNET_AUTO_TRACES_ASPNET_INSTRUMENTATION_ENABLED = false), the application works fine and there was no exception. I tried with Opentelemetry .NET instrumentation versions 1.2.0, 1.4.0 and 1.7.0. All behave same way.
Is the Opentelemetry Asp Net Instrumentation locks the request headers of some think like this which affects the other middlewares. My middleware was not able to set a custom header to the http request headers.

But the instrumentation works and I could see the traces in the OTel Collector.

### Steps to Reproduce

1. Create a .NET Framework 4.7 Web application. Create a OWIN based middleware to set a custom request header. Create a web api for testing the middleware. You can get the project code in this github repo. https://github.com/rahjesh-vunet/Opentelemetry-AspNet-Instrumentation-Issue
2. Deploy the application in IIS and access the API http://localhost/api/test. You can see the api gives the output. "<string xmlns="http://schemas.microsoft.com/2003/10/Serialization/">Hello, world111111111111111!</string>"
3. Instrument this application running in IIS using the powershell script from https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/releases/tag/v1.7.0
4. Now access the API and you will see error.
5. Add the variable "OTEL_DOTNET_AUTO_TRACES_ASPNET_INSTRUMENTATION_ENABLED" to false in the "Application Settings" of your application in IIS. Restart IIS and check the API and it will work again.

### Expected Result

The API works even after Opentelemetry .NET instrumentation

### Actual Result

image_720

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by lachmatt**
## Why

Fixes #3589 

## What

Linked issue stems from the fact that WCF instrumentation initialization was run when `System.ServiceModel` assembly was loaded. Initialization included setting up WCF instrumentation options, and initializing [parent span correction feature](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/88de33c3383118e5f8d864987400a23aa4e64c64/src/OpenTelemetry.Instrumentation.Wcf/Implementation/AspNetParentSpanCorrector.cs). This feature hooks into ASP.NET instrumentation, modifies the request headers and assumes [request headers are read-only](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/88de33c3383118e5f8d864987400a23aa4e64c64/src/OpenTelemetry.Instrumentation.Wcf/Implementation/AspNetParentSpanCorrector.cs#L48-L58).
This was causing issues for OWIN app hosed in IIS that attempted to modify request headers with a OWIN middleware.

This PR moves initialization to bytecode instrumentation.

## Tests

Included in PR.

## Checklist

- [x] `CHANGELOG.md` is updated.
~~- [ ] Documentation is updated.~~
- [x] New features are covered by tests.

### CODE REVIEW

File: build/Projects.cs [hunk 1]
```diff
@@ -24,9 +24,10 @@ public static class Tests
         public static class Applications
         {
             public const string AspNet = "TestApplication.AspNet.NetFramework";
+            public const string ContinuousProfilerNativeDep = "TestApplication.ContinuousProfiler.NativeDep";
+            public const string Owin = "TestApplication.Owin.IIS";
```
Comment (Kielek) [inline build/Projects.cs:28]:
```suggestion
            public const string OwinIis = "TestApplication.Owin.IIS";
```

File: test/test-applications/integrations/TestApplication.Owin.IIS/Properties/AssemblyInfo.cs [hunk 2]
```diff
@@ -0,0 +1,35 @@
...
+//
+//      Major Version
+//      Minor Version 
+//      Build Number
+//      Revision
+//
+// You can specify all the values or you can default the Revision and Build Numbers 
+// by using the '*' as shown below:
+[assembly: AssemblyVersion("1.0.0.0")]
+[assembly: AssemblyFileVersion("1.0.0.0")]
```
Comment (Kielek) [inline test/test-applications/integrations/TestApplication.Owin.IIS/Properties/AssemblyInfo.cs:35]: Is it really needed?

Comment (lachmatt) [reply test/test-applications/integrations/TestApplication.Owin.IIS/Properties/AssemblyInfo.cs:35]: It was automatically generated.

**Review by pjanotti — APPROVED** [review]

**Review by nrcventura — APPROVED** [review]

**Review by Kielek — APPROVED** [review]
